In [1]:
import numpy as np
import pandas as pd

In [3]:
b = pd.Series([0,1,2,3])
b

0    0
1    1
2    2
3    3
dtype: int64

In [4]:
q = b.drop([0])

In [9]:
b.to_pickle('b.pkl')

In [16]:
a[[0, 2], :]

array([[12,  3,  8, 20],
       [15,  7, 19,  7]])

In [24]:
idx = a.argsort(axis = 0)

In [26]:
a

array([[12,  3,  8, 20],
       [11, 17, 19,  7],
       [15,  7, 19,  7]])

In [32]:
np.save('qwe.txt2', a)

In [34]:
b = np.load('qwe.txt2.npy')

In [35]:
b

array([[12,  3,  8, 20],
       [11, 17, 19,  7],
       [15,  7, 19,  7]])

In [2]:
import pandas as pd 
import numpy as np